accepted = [
    "AGPL-3.0",
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "Unicode-DFS-2016",
]

[typenum.clarify]
license = "MIT OR Apache-2.0"

[[typenum.clarify.files]]
path = "LICENSE"
license = "MIT OR Apache-2.0"
checksum = "db11fec9946737df39ca3898d9cd8c10ec6f6c3a884a6802b0ad0b81b4e8f23a"

[[typenum.clarify.files]]
path = "LICENSE-APACHE"
license = "Apache-2.0"
checksum = "516b24e051bf5630880ebbd55c40a25ce9552ebaf8970a53e8976eb70e522406"

[[typenum.clarify.files]]
path = "LICENSE-MIT"
license = "MIT"
checksum = "a825bd853ab71619a4923d7b4311221427848070ff44d990da39b0b274c1683f"

[unicode_categories.clarify]
license = "MIT OR Apache-2.0"

[[unicode_categories.clarify.files]]
path = "LICENSE-APACHE"
license = "Apache-2.0"
checksum = "c6596eb7be8581c18be736c846fb9173b69eccf6ef94c5135893ec56bd92ba08"

[[unicode_categories.clarify.files]]
path = "LICENSE-MIT"
license = "MIT"
checksum = "98a817e7b85e5fe4e79d165c656a4a139793b8b643d0f3d9cbcc3538ef82ec82"
