[package]
name = "firehose"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
askama = { version = "0.11.2", features = ["with-axum"] }
askama_axum = "0.1.0"
axum = "0.5.1"
axum-extra = { version = "0.3.3", features = ["cookie-private", "cookie"] }
axum_csrf = "0.3.0"
base64 = "0.13.0"
chrono = "0.4.19"
cookie = { version = "0.16.0", features = ["private"] }
hyper = "0.14.18"
serde = { version = "1.0.137", features = ["derive"] }
sqlx = { version = "0.5.13", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }
tower = "0.4.12"
tower-http = { version = "0.3.3", features = ["trace", "request-id"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
uuid = { version = "0.8.2", features = ["v4"] }

[patch.crates-io]
askama = { git = 'https://github.com/djc/askama' }
askama_axum = { git = 'https://github.com/djc/askama' }
axum_csrf = { path = "../axum_csrf" }
