[package]
name = "firehose"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
askama = { version = "0.11.2", features = ["with-axum"] }
askama_axum = "0.1.0"
axum = "0.5.1"
base64 = "0.13.0"
chrono = "0.4.19"
cookie = { version = "0.16.0", features = ["signed"] }
hyper = "0.14.18"
serde = { version = "1.0.136", features = ["derive"] }
sqlx = { version = "0.5.11", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
thiserror = "1.0.31"
tokio = { version = "1.17.0", features = ["full"] }
tower = "0.4.12"
tower-cookies = { version = "0.6.0", features = ["signed"] }
tower-http = { version = "0.2.5", features = ["trace", "request-id"] }
tracing = "0.1.32"
tracing-subscriber = { version = "0.3.10", features = ["env-filter"] }
uuid = { version = "0.8.2", features = ["v4"] }

[patch.crates-io]
askama = { git = 'https://github.com/djc/askama' }
askama_axum = { git = 'https://github.com/djc/askama' }
