[package]
name = "metagram"
version = "0.1.0"
edition = "2021"
default-run = "server"

[dependencies]
addr = "0.15.4"
anyhow = "1.0.57"
askama = { version = "0.11.2", features = ["with-axum"] }
askama_axum = "0.1.0"
async-trait = "0.1.56"
axum = { version = "0.5.1", features = ["headers"] }
axum-extra = { version = "0.3.3", features = ["cookie-private", "cookie", "typed-routing", "spa"] }
axum_csrf = "0.4.0"
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.2.14", features = ["derive"] }
cookie = { version = "0.16.0", features = ["private"] }
derivative = "2.2.0"
envy = "0.4.2"
fake = "2.5.0"
http = "0.2.7"
hyper = "0.14.18"
lazy_static = "1.4.0"
mockall = "0.11.1"
r2d2 = "0.8.10"
rand = "0.8.5"
regex = "1.6.0"
serde = { version = "1.0.137", features = ["derive"] }
sqlx = { version = "0.6.1", features = ["runtime-tokio-native-tls", "postgres", "chrono", "uuid"] }
stytch = { git = "https://github.com/jdkaplan/stytch-rust" }
tabwriter = "1.2.1"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }
tower = "0.4.12"
tower-http = { version = "0.3.3", features = ["trace", "request-id", "fs"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter", "json"] }
url = "2.2.2"
uuid = { version = "1.1.2", features = ["v4", "serde"] }

[patch.crates-io]
askama = { git = 'https://github.com/djc/askama' }
askama_axum = { git = 'https://github.com/djc/askama' }

[dev-dependencies]
axum-macros = "0.2.3"

[package.metadata.cargo-machete]
ignored = [
    # Implement axum's IntoResponse for askama's Template. This usage is a
    # false-positive for machete.
    "askama_axum",
]
