[package]
name = "firehose"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
askama = { version = "0.11.2", features = ["with-axum"] }
askama_axum = "0.1.0"
async-trait = "0.1.56"
axum = { version = "0.5.1", features = ["headers"] }
axum-extra = { version = "0.3.3", features = ["cookie-private", "cookie"] }
axum_csrf = "0.4.0"
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
cookie = { version = "0.16.0", features = ["private"] }
derivative = "2.2.0"
http = "0.2.7"
http-serde = "1.1.0"
hyper = "0.14.18"
mockall = "0.11.1"
reqwest = { version = "0.11.10", features = ["json"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.82"
sqlx = { version = "0.5.13", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }
tower = "0.4.12"
tower-http = { version = "0.3.3", features = ["trace", "request-id"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
url = "2.2.2"
uuid = { version = "0.8.2", features = ["v4", "serde"] }

[patch.crates-io]
askama = { git = 'https://github.com/djc/askama' }
askama_axum = { git = 'https://github.com/djc/askama' }
