services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
    ports:
      - "${PGPORT}:5432"
    volumes:
      - ./docker/dev-postgres/initdb.d:/docker-entrypoint-initdb.d
