services:
  db_development:
    image: postgres:13
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB: "${PGDATABASE}"
    ports:
      - "${PGPORT}:5432"
  db_test:
    image: postgres:13
    environment:
      POSTGRES_USER: "${TEST_PG_USER}"
      POSTGRES_PASSWORD: "${TEST_PG_PASSWORD}"
      POSTGRES_DB: "${TEST_PG_DATABASE}"
    ports:
      - "${TEST_PG_PORT}:5432"
