kill_signal = "SIGTERM"
kill_timeout = 60
processes = []

[deploy]
release_command = "drift migrate"

[env]
BASE_URL = 'https://metagram.net/'

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
internal_port = 8000
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[services.http_checks]]
interval = "10s"
grace_period = "5s"
method = "get"
path = "/.well-known/health-check"
protocol = "http"
restart_limit = 0
timeout = "2s"
tls_skip_verify = false

[services.http_checks.headers]
