name: Test

on:
  pull_request:
  push:
    branches:
      - main

env:
  SQLX_OFFLINE: true

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.63
          components: rustfmt

      - run: cargo fmt --all --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.63
          components: clippy

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: metagram_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      lorem-rss:
        image: evdb/lorem-rss@sha256:39b550fb45f4780bb651c2352754c4654d261dfcf2a8e63f96b0a91dcbe6cc0b
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.63

      - run: cargo install --git https://github.com/jdkaplan/drift

      - run: drift migrate
        env:
          DRIFT_DATABASE_URL: "postgres://postgres:postgres@localhost:5432/metagram_test"

      - run: cargo test
        env:
          TEST_DATABASE_URL: "postgres://postgres:postgres@localhost:5432/metagram_test"
          LOREM_RSS_URL: "http://localhost:5000/"
